title: "Himanshu's Portfolio"
description: "Highlighting My Cybersecurity Journey: A Portfolio of Skills, Projects, and Real-World Threat Analysis"
remote_theme: pages-themes/hacker@v0.2.0
theme: jekyll-theme-hacker
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
include: pages
external:
  linkedin: "https://www.linkedin.com/in/-himanshu/"
  medium: "https://medium.com/@hexc0de"
